### ISSUE TITLE
Deploy on GCP

### ISSUE THREAD

**Issue by adamperer** [cmuvis/mlint#22]

**Comment by yzd1998111** [comment]
The 502 bad gateway showed up again during deployment and I eventually solve the issue. The app is now up running.

The cause is either memory (originally 1gb, now 4gb)of vm running the app being too small or missing handler in app.yaml file. 

I don't know which one of these caused the bad gateway issue because I made these two changes simultaneously in the last deployment but it is certainly one of them.
