### ISSUE TITLE
Point Scoring

### ISSUE THREAD

**Issue by laurafulton** [cmuvis/mlint#40]
Guessers + Explainers get the same # of points
After each reveal give # of points:
1 explaination - 25
2 explaination - 20
3 explaination - 15
4 explaination -10
hint - 5

**Comment by yzd1998111** [comment]
1. I took your advice but added 5 points for guessing correctly in 1-4. This is because there are 5 rounds(not counting the hint selection round) in total. 

In the 1-4th round, a new hint image is revealed. 
In the 5th round, the player is given the category of the answer, so he/she should still be able to earn more points by guessing correctly in this round than doing the multiple-choice question correctly in the end. 

So now, the # of points rewarded is calculated as 35 - 5 * roundNumber.

2.  For the hint round, 10 points are rewarded if another player guesses correctly based on your hints. So ideally, selecting good hints and making guesses are always rewarded.

**Comment by yzd1998111** [comment]
@adamperer 

Thanks for uploading the correct images! Just don't forget to change the number of images to be loaded after adding them. They were not showing up correctly since they were not loaded at the beginning of the file. 

Example in visualization.js (or search: mixed among all files):
for(let i = 0; i < 528; i++){
    vis[i] = require('../image/mixed4d/'+ (i) +'.png')
}
I changed the number to 528 from 4xx because some images were added but not loaded.
