### ISSUE TITLE
Log-in button position new landing page

### ISSUE THREAD

**Issue by laurafulton** [cmuvis/mlint#45]
Position of log-in from upper right to next to 'How To'

**Comment by yzd1998111** [comment]
Changed the position of the sign-in button and kept the functionality, but @kazijawad might also want to look at the changes in the landing.scss file to do some further style fixes. 

@kazijawad, don't forget to at least keep some records of what you deleted when you add some files. Previously you deleted the startNewLog() in onClick for the "Start to Play" button in the main menu but forgot to add it for the new "Start to Play". All logs in firebase afterward have no timestamp attached but null. Also, the "Play Again" button seems to be broken again, you might have to take a look at that to see if it is also related to your changes since I did not work on the app last week.

**Comment by kazijawad** [comment]
Ok thank you for that, I know the problem with the "Play Again" button and will fix that right away. I'll be more careful with modifying the code. I didn't realize I removed the logging!
