### ISSUE TITLE
Visualizations not showing up for new categories

### ISSUE THREAD

**Issue by laurafulton** [cmuvis/mlint#47]
Look into repo and how new images are stores/retrieved. 
<img width="857" alt="Screen Shot 2020-04-01 at 12 03 50 PM" src="https://user-images.githubusercontent.com/9020517/78167849-27461780-741d-11ea-9a9e-beab7d187a21.png">

**Comment by kazijawad** [comment]
I realized the issue with this. All the old feature visualizations had a total of 10 image urls. However, the new feature visualizations have a total of 8 image urls. That's why the screenshot for certain categories have only 8 images. We could either make the page show 8 images or two new feature visualizations could be made for all the new images. Let me know what you guys think is best!

**Comment by laurafulton** [comment]
I think generating 2 more, would be great for consistency. Maybe Jiachen can weigh in tomorrow from a data perspective.

**Comment by laurafulton** [comment]
@jcho17 generating additional images :)
